[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "../netlify-plugin-cloudinary"
  # package = "./plugins/netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "colbycloud"